---
- name: macOS
  hosts: localhost
  # pre_tasks:
  tasks:
    - include_tasks: ./ansible/zsh.yml
    - include_tasks: ./ansible/tmux.yml
    - include_tasks: ./ansible/nvim.yml
    - include_tasks: ./ansible/yabai.yml
  tags: always

