---
- name: macOS
  hosts: localhost
  # pre_tasks:
  tasks:
    - import_tasks: ./ansible/zsh.yml
    - import_tasks: ./ansible/tmux.yml
    - import_tasks: ./ansible/nvim.yml
    - import_tasks: ./ansible/yabai.yml
