- name: tmux brew
  homebrew:
    name: [ "tmux", "fzf", "reattach-to-user-namespace"]
    state: latest
  tags:
    - tmux

- name: .tmux.conf 
  command: "cp ~/.dotfiles/.tmux.conf ~/"
  tags:
    - tmux
    - conf

-  name: tpm exists
   stat:
     path: "~/.tmux/plugins/tpm"
   register: tpm 
   tags:
    - tmux

- name: tpm clone
  ansible.builtin.git: 
    repo: "git@github.com/tmux-plugins/tpm"
    bare: true
    dest: "~/.tmux/plugins/tpm"
  when: tpm.stat.exists == True
  tags:
    - tmux

- name: tmux sessionizer 
  command: "chmod +x ~/.dotfiles/scripts/tmux-sessionizer"
  tags:
    - tmux

- name: tmux reload
  command: "tmux source-file ~/.tmux.conf"
  tags:
    - tmux
    - conf

