#!/usr/bin/env bash

PANE_PERCENTAGE=30

q_pane=$(tmux list-panes -F "#{pane_id}:#{pane_current_command}" | grep "kiro-cli" | cut -d: -f1)

if [ -n "$q_pane" ]; then
    pane_width=$(tmux display-message -t "$q_pane" -p "#{pane_width}")
    window_width=$(tmux display-message -p "#{window_width}")
    pane_percent=$((pane_width * 100 / window_width))

    if [ "$pane_percent" -gt 5 ]; then
        tmux resize-pane -t "$q_pane" -x 1%
        tmux select-pane -L
    else
        tmux resize-pane -t "$q_pane" -x $PANE_PERCENTAGE%
        tmux select-pane -t "$q_pane"
    fi
else
    tmux split-window -h -p $PANE_PERCENTAGE -c "#{pane_current_path}" "kiro-cli"
fi
