- name: nvim brew
  homebrew:
    name: [ "neovim", "lua", "luarocks" ] 
    state: latest
  tags:
    - nvim

-  name: nvim exists
   stat:
     path: "~/.config/nvim"
   register: nvim 
   tags:
    - nvim

- name: nvim clone
  ansible.builtin.git: 
    repo: 'git@github.com/jakebark/nvim.git' 
    bare: true
    dest: "~/.config/nvim"
  when: nvim.stat.exists == False
  tags:
    - nvim

- name: nvim pull
  git:
    repo: "https://github.com/jakebark/nvim"
    dest: "~/.config/nvim"
    update: yes
    force: true
  when: nvim.stat.exists == True
  tags:
    - nvim
