- name: tmux brew
  homebrew:
    name: [ "tmux", "fzf" ]
    state: latest
  tags:
    - tmux

- name: .tmux.conf 
  command: "cp ~/.dotfiles/.tmux.conf ~/"
  tags:
    - tmux
    - conf

- name: tmux reload
  command: "tmux source-file ~/.tmux.conf"
  tags:
    - tmux
    - conf

- name: tmux sessionizer 
  command: "chmod +x ~/.dotfiles/scripts/tmux-sessionizer"
  tags:
    - tmux
