- name: nvim apt
  apt:
    name: neovim 
    state: present
  tags:
    - nvim

- name: packer
  ansible.builtin.git:
    repo: 'https://github.com/wbthomason/packer.nvim'
    dest: "{{ lookup('env', 'HOME') }}/.local/share/nvim/site/pack/packer/start/packer.nvim"
  tags:
    - nvim

-  name: nvim exists
   stat:
     path: "~/.config/nvim"
   register: nvim 
   tags:
    - nvim

- name: nvim clone
  git:
    repo: "https://github.com/jakebark/nvim"
    dest: "~/.config/nvim"
    clone: yes
  when: nvim.stat.exists == False
  tags:
    - nvim

- name: nvim pull
  git:
    repo: "https://github.com/jakebark/nvim"
    dest: "~/.config/nvim"
    update: yes
    force: true
  when: nvim.stat.exists == True
  tags:
    - nvim
